[package]
name = "incro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-ffi = "0.5.0"
evdev = { version = "0.12.1", features = ["tokio"] }
libloading = "0.8.1"
tokio = { version = "1.33.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"
